project_id = "rtlbnrgszuwdpvmquyis"

[functions.organize-questions]
verify_jwt = false

[functions.treino-dicas]
verify_jwt = false

[functions.emergency-data]
verify_jwt = false

[functions.petzinho-ia]
verify_jwt = false